# See:
# - https://github.com/DavidAnson/markdownlint/tree/main/doc
# - https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml

# MD004/ul-style
MD004:
  style: "dash"

# MD013/line-length
MD013: false

# MD033/no-inline-html
MD033:
  allowed_elements: ["br"]

# MD049/emphasis-style
MD049:
  style: "asterisk"

# MD050/strong-style
MD050:
  style: "asterisk"
