services:
  postgres:
    image: postgres:18rc1
    container_name: pg18-uuidv7
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-testdb}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 30s
      timeout: 10s
      retries: 3

  dbmate:
    image: amacneil/dbmate:2
    container_name: dbmate
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./db:/db
    depends_on:
      postgres:
        condition: service_healthy
    profiles:
      - migration

volumes:
  postgres_data:
