version: "3"

tasks:
  check:
    desc: "Check Markdown"
    cmds:
      - task: fix
      - task: lint

  fix:
    desc: "Auto fix Markdown"
    cmds:
      - task: lint-fix

  lint:
    desc: "Run markdownlint on project markdown files"
    cmds:
      - markdownlint .

  lint-fix:
    desc: "Fix markdownlint issues automatically"
    cmds:
      - markdownlint . --fix
