name: Check JSON

on:
  push:
    paths:
      - "**/*.json"
      - ".github/workflows/check-json.yml"
  pull_request:
    paths:
      - "**/*.json"
      - ".github/workflows/check-json.yml"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install mise and setup
        uses: jdx/mise-action@v3
        with:
          install: true
          install_args: "biome"
          cache: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fix
        run: task json:fix

      - name: Commit and Push
        uses: satt-dots/simple-commit-and-push@v1
        with:
          commit-message: "Auto fix code by `task json:fix`"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check
        run: task json:check
